refactor(connection): refactor mqtt/edgex connection share
lf-edge/ekuiper pull request #1183
Opened 2022-02-22 09:19 UTC by SuperRxan

Signed-off-by: Jianxiang Ran <rxan_embedded@163.com>

2022-02-22 10:17 UTC, ngjaying requested changes
Shall we name these resource?

2022-02-22 10:17 UTC, ngjaying commented on internal/topo/connection/clients/mqtt/mqtt_wrapper.go
> +	subId := fmt.Sprintf("%s_%s_%d", c.GetRuleId(), c.GetOpId(), c.GetInstanceId())
Is this needed? Do not do such calculation in a very high frequency op

2022-02-22 10:17 UTC, ngjaying commented on internal/topo/connection/clients/mqtt/mqtt_wrapper.go
> +	subId := fmt.Sprintf("%s_%s_%d", c.GetRuleId(), c.GetOpId(), c.GetInstanceId())
Is it possible to calculated beforehand and save?

2022-02-22 10:17 UTC, ngjaying commented on internal/topo/connection/clients/mqtt/mqtt_wrapper.go
> +	subId := fmt.Sprintf("%s_%s_%d", c.GetRuleId(), c.GetOpId(), c.GetInstanceId())
If this is only run once, then it is ok

2022-02-22 10:17 UTC, ngjaying commented on internal/topo/connection/clients/mqtt/mqtt_wrapper.go
> +		if found {
what about qos different

2022-02-22 10:17 UTC, ngjaying commented on internal/topo/connection/clients/edgex/edgex_wrapper.go
> +	subId := fmt.Sprintf("%s_%s_%d", c.GetRuleId(), c.GetOpId(), c.GetInstanceId())
do not calculate this everytime

2022-02-22 10:33 UTC, ngjaying commented on internal/topo/connection/clients/mqtt/mqtt_wrapper.go
> +			for _, consumer := range sub.topicConsumers {
The broadcast here may be blocked forever?

2022-02-22 10:36 UTC, ngjaying commented on internal/topo/source/mqtt_source.go
> +	messages := make(chan types.MessageEnvelope)
won't be closed

2022-03-01 01:44 UTC, SuperRxan commented on internal/topo/connection/clients/mqtt/mqtt_wrapper.go
> +		if found {
will document this

2022-03-01 02:19 UTC, ngjaying requested changes
Some small problems

2022-03-01 02:19 UTC, ngjaying commented on pkg/api/stream.go
> +	"github.com/edgexfoundry/go-mod-messaging/v2/pkg/types"
Don't import these implementations in the api package

2022-03-01 02:19 UTC, ngjaying commented on pkg/api/stream.go
> +type MessageEnvelope struct {
Don't put these structs?

2022-03-01 02:19 UTC, ngjaying commented on internal/topo/connection/factory/buildin.go
> +
filename should be builtin

2022-03-01 02:19 UTC, ngjaying commented on internal/topo/connection/clients/mqtt/mqtt_wrapper.go
> +				default:
Print a log here

2022-03-01 02:19 UTC, ngjaying commented on internal/topo/connection/clients/edgex/edgex_wrapper.go
> +						default:
print some log here

2022-03-01 07:58 UTC, ngjaying approved these changes

2022-03-01 07:59 UTC, merged