fea(sql): add when condition for analytic function
lf-edge/ekuiper pull request #1534
Opened 2022-11-24 12:38 UTC by superrxan

2022-11-24 13:34 UTC, ngjaying requested changes

2022-11-24 13:34 UTC, ngjaying commented on internal/binder/function/funcs_analytic.go
> +			if args[0].(bool) && args[1] == nil {
Maybe panic if args[0] is not a bool

2022-11-24 13:34 UTC, ngjaying commented on internal/binder/function/funcs_analytic.go
> +			key := args[len(args)-1].(string)
The same problem as above

2022-11-24 13:34 UTC, ngjaying commented on internal/binder/function/funcs_analytic.go
> +			validData := args[len(args)-2].(bool)
same problem

2022-11-24 13:34 UTC, ngjaying commented on internal/binder/function/funcs_analytic.go
> +			key := args[len(args)-1].(string)
same problem

2022-11-24 14:02 UTC, superrxan commented on internal/binder/function/funcs_analytic.go
> +			if args[0].(bool) && args[1] == nil {
validate stage can check this error

2022-11-24 14:02 UTC, superrxan commented on internal/binder/function/funcs_analytic.go
> +			key := args[len(args)-1].(string)
validate stage can check this error

2022-11-25 01:11 UTC, ngjaying approved these changes

2022-11-25 01:11 UTC, merged

2022-11-25 09:01 UTC, ngjaying commented
Closes #1498