fea(config): Full data export import
lf-edge/ekuiper pull request #1573
Opened 2022-12-21 02:17 UTC by superrxan

2022-12-22 08:53 UTC, ngjaying requested changes

2022-12-22 08:53 UTC, ngjaying commented on internal/server/rest.go
> +	r.HandleFunc("/config/export", configurationExportHandler).Methods(http.MethodGet)
name it data/export, data/import

2022-12-22 08:53 UTC, ngjaying commented on cmd/kuiper/main.go
> +					Usage: "\"import configuration -f configuration_file",
name it data export and data import

2022-12-23 09:08 UTC, superrxan commented on internal/server/rest.go
> +	r.HandleFunc("/config/export", configurationExportHandler).Methods(http.MethodGet)
ack

2022-12-23 09:21 UTC, ngjaying approved these changes

2022-12-23 09:21 UTC, merged