fix (function): make aggregate functions return the same value as the SQL for empty Windows
lf-edge/ekuiper pull request #1690
Opened 2023-03-23 09:10 UTC by Rui-Gan

Closes #1682

2023-03-23 10:25 UTC, superrxan approved these changes

2023-03-24 02:19 UTC, ngjaying requested changes

2023-03-24 02:19 UTC, ngjaying commented on internal/binder/function/funcs_agg.go
> +			return []interface{}{}, nil
The second argument 'all' means whether to reutrn the full array or just a single event. Here, we need to return a single event -> nil

2023-03-24 03:44 UTC, ngjaying approved these changes

2023-03-24 03:44 UTC, merged