feat: add explain rest api for sql_rule
lf-edge/ekuiper pull request #1943
Opened 2023-05-26 04:12 UTC by xuyukeviki

See https://or28elw3b5.feishu.cn/docx/WZoedzBceoqgNBxoEbUcevrTntf for details

2023-05-26 06:03 UTC, ngjaying commented
Thanks @xuyukeviki. Please follow the DCO check link to pass it.
Additionally, we prefer linear history, so please rebase your commits. Check https://github.com/lf-edge/ekuiper/blob/master/docs/en_US/CONTRIBUTING.md for detail.

2023-05-26 08:12 UTC, xuyukeviki commented
> Thanks @xuyukeviki. Please follow the DCO check link to pass it. Additionally, we prefer linear history, so please rebase your commits. Check https://github.com/lf-edge/ekuiper/blob/master/docs/en_US/CONTRIBUTING.md for detail.

done

2023-05-26 08:14 UTC, ngjaying commented
> > Thanks @xuyukeviki. Please follow the DCO check link to pass it. Additionally, we prefer linear history, so please rebase your commits. Check https://github.com/lf-edge/ekuiper/blob/master/docs/en_US/CONTRIBUTING.md for detail.
> 
> done

DCO is still not passed. Try not to use merge commit, use rebase instead.

2023-05-29 03:36 UTC, Yisaer requested changes
Could u split the pr into serval pr and write the unit test for the explain info of logical plans?

2023-05-29 03:36 UTC, Yisaer commented on internal/topo/planner/logicalPlan.go
> +	return s[1]
I don't think `reflect` is a proper way to get the type string, I tend to initialize the type string during init logical plan like tidb

https://github.com/pingcap/tidb/blob/6888a1aa6b0f31b1c23e28bc7811bcdf2c5e5ddf/planner/core/initialize.go#L41-L44

2023-05-29 03:36 UTC, Yisaer requested changes
Could u split the pr into serval pr and write the unit test for the explain info of logical plans?

2023-06-19 01:59 UTC, closed without merging