feat: support delay slidingWindow
lf-edge/ekuiper pull request #2005
Opened 2023-06-19 09:24 UTC by Yisaer

2023-06-20 08:14 UTC, ngjaying requested changes
For event time, do not handle delay in watermark_op. Handle it in event_timer_triggerer. Addtitionally, we should add test cases in topo_test, testWidnow and testEventWindow.

2023-06-20 08:14 UTC, ngjaying commented on internal/topo/node/watermark_op.go
> +			if w.delay > 0 {
This is wrong. Watermark has nothing to do with the processing time (real time). It only deals with the event time. This op is dedicated to send out watermark tuple (tick) and do not need to deal with logics like delay.

2023-06-25 10:35 UTC, ngjaying commented
Please add doc as well

2023-06-26 08:22 UTC, Yisaer commented
> Please add doc as well

updated.

2023-06-26 09:59 UTC, ngjaying reviewed
A question about event window imp

2023-06-26 09:59 UTC, ngjaying commented on internal/topo/node/event_window_trigger.go
> +						if o.window.Delay > 0 && o.window.Type == ast.SLIDING_WINDOW {
Is it better to calculate the window end in the getNextWindow() to unify the processing?

2023-06-27 03:21 UTC, ngjaying approved these changes
Great work!

2023-06-27 03:21 UTC, merged