fix(sourceNode): set sourceOption.SCHEMAID by props
lf-edge/ekuiper pull request #2116
Opened 2023-07-20 07:03 UTC by cea5

fix bug :schemaName and schemaMessage not set
![image](https://github.com/lf-edge/ekuiper/assets/17960530/c0f330fb-1225-4b37-9ff5-0b940c1e2375)

2023-07-20 07:05 UTC, ngjaying commented
Thank you! Please follow the DCO Details link to pass it.

2023-07-20 07:47 UTC, ngjaying requested changes

2023-07-20 07:47 UTC, ngjaying commented on internal/topo/planner/planner_graph.go
> +		sourceOption.SCHEMAID = gn.Props["schemaName"].(string) + "." + gn.Props["schemaMessage"].(string)
Should only override schemaId if both schemaName and schemaMessage are set. Additionally, need to check if the props are string type or they will be a panic here.

2023-07-20 09:08 UTC, ngjaying commented
LGTM, thank you! Will merge once all checks passed

2023-07-21 00:38 UTC, ngjaying requested changes
go fmt is required in this project.

2023-07-21 00:38 UTC, ngjaying commented on internal/topo/planner/planner_graph.go
> +		if sourceOption.SCHEMAID == "" && gn.Props["schemaName"] != nil && gn.Props["schemaMessage"] != nil{
add a space after nil :  "nil{" -> "nil {"

2023-07-21 00:38 UTC, ngjaying commented on internal/topo/planner/planner_graph.go
> +				sourceOption.SCHEMAID = schemaName+"."+schemaMessage
Add spaces between + :  schemaName + "." + schemaMessage

2023-07-21 02:17 UTC, ngjaying requested changes
Is it possible for you to add a test case? We can help if you have difficulties.

2023-07-21 02:39 UTC, cea5 commented
ok, I will try to add one.

2023-07-26 01:09 UTC, ngjaying requested changes

2023-07-26 01:09 UTC, ngjaying commented on internal/topo/planner/planner_graph_test.go
> +    {
The indention format is wrong, please fix.

2023-07-26 03:11 UTC, ngjaying approved these changes

2023-07-26 03:11 UTC, merged

2023-07-26 03:11 UTC, ngjaying commented
Merged, thank you!