Refactor connector
lf-edge/ekuiper pull request #2219
Opened 2023-08-30 07:21 UTC by LenaLenaPan

Signed-off-by: LenaLenaPan 
hilena.pan@gmail.com

2023-08-31 01:44 UTC, ngjaying commented on docs/en_US/guide/sources/builtin/mqtt.md
> +```json
should be yaml

2023-08-31 01:59 UTC, ngjaying requested changes

2023-08-31 01:59 UTC, ngjaying commented on docs/en_US/guide/sources/builtin/edgex.md
> +2. Use the `create` command to create a rule, specifying the EdgeX connector as its source, for example: <!--the command need to be further confirmed-->
This is right, we can remove the comment

2023-09-01 01:35 UTC, LenaLenaPan commented on docs/en_US/guide/sources/builtin/mqtt.md
> +```json
@ngjaying updated

2023-09-01 03:32 UTC, ngjaying approved these changes

2023-09-01 03:33 UTC, merged