Add support for TLSMinVersion and RenegotiationOptions for mqtt and http
lf-edge/ekuiper pull request #2258
Opened 2023-09-14 06:49 UTC by tfoldi

Support for extra SSL parameters for `mqtt` and `http` sources. Fixes #2241

2023-09-14 06:51 UTC, tfoldi commented on internal/pkg/cert/cert.go
> +	conf.Log.Infof("=> TLS configs: %v.", tlsConfig)
I will remove this line after testing it in a couple of scenarios

2023-09-19 00:58 UTC, ngjaying requested changes

2023-09-19 00:58 UTC, ngjaying commented on internal/io/http/client.go
> +	TLSMinVersion        string      `json:"TLSMinVersion"`
Can we follow the convention of other properties here. `json:"TLSMinVersion"` ->  `json:"tlsMinVersion"`

2023-09-19 00:58 UTC, ngjaying commented on internal/topo/connection/clients/mqtt/mqtt.go
> +	TLSMinVersion        string `json:"TLSMinVersion"`
The same here

2023-09-24 10:25 UTC, ngjaying requested changes
LGTM. Just need to pass markdown check. Additionally, it'll be better to increase ut coverage to pass the condecov check. Thanks.

2023-09-24 10:52 UTC, tfoldi commented
> LGTM. Just need to pass markdown check. Additionally, it'll be better to increase ut coverage to pass the condecov check. Thanks.

The markdown check fails in a file that I did not touch. Actually it is failing due to #2272 committed by @Yisaer  two days ago (see https://github.com/lf-edge/ekuiper/actions/runs/6269824039/job/17026819627).

```
Run markdownlint -c .github/workflows/markdown_config.json ./docs/
  markdownlint -c .github/workflows/markdown_config.json ./docs/
  shell: /usr/bin/bash -e {0}
docs/en_US/configuration/global_configurations.md:[2](https://github.com/lf-edge/ekuiper/actions/runs/6287798441/job/17072623952?pr=2258#step:4:2)[5](https://github.com/lf-edge/ekuiper/actions/runs/6287798441/job/17072623952?pr=2258#step:4:6)9 MD012/no-multiple-blanks Multiple consecutive blank lines [Expected: 1; Actual: 2]
```

Locally, the markdown test passes so "it's not me, it's you" :)

```
❯ markdownlint -c .github/workflows/markdown_config.json docs
❯ echo $?
0
```

For tests, sure, I can add tests for those lines.

2023-09-24 11:01 UTC, ngjaying commented
> > LGTM. Just need to pass markdown check. Additionally, it'll be better to increase ut coverage to pass the condecov check. Thanks.
> 
> The markdown check fails in a file that I did not touch. Actually it is failing due to #2272 committed by @Yisaer two days ago (see https://github.com/lf-edge/ekuiper/actions/runs/6269824039/job/17026819627).
> 
> ```
> Run markdownlint -c .github/workflows/markdown_config.json ./docs/
>   markdownlint -c .github/workflows/markdown_config.json ./docs/
>   shell: /usr/bin/bash -e {0}
> docs/en_US/configuration/global_configurations.md:[2](https://github.com/lf-edge/ekuiper/actions/runs/6287798441/job/17072623952?pr=2258#step:4:2)[5](https://github.com/lf-edge/ekuiper/actions/runs/6287798441/job/17072623952?pr=2258#step:4:6)9 MD012/no-multiple-blanks Multiple consecutive blank lines [Expected: 1; Actual: 2]
> ```
> 
> Locally, the markdown test passes so "it's not me, it's you" :)
> 
> ```
> ❯ markdownlint -c .github/workflows/markdown_config.json docs
> ❯ echo $?
> 0
> ```
> 
> For tests, sure, I can add tests for those lines.

Ah, it's weird. The markdown check should have run in that PR. Never mind, we'll fix that. Appreciate your patience.

2023-09-26 02:12 UTC, Yisaer commented
plz update the base master branch as we have fixed the markdown lint error

2023-09-28 01:39 UTC, ngjaying approved these changes
LGTM. What a long run, thanks for the patience.

2023-09-28 01:39 UTC, merged