feat: add -json flag to describe
lf-edge/ekuiper pull request #2286
Opened 2023-10-05 17:16 UTC by jerempy

Add ability to get output from describe as json format.

Closes: [#186](https://github.com/lf-edge/ekuiper/issues/186)

I added a converter to parse the regular describe return val. I did this so as not to pass a flag all the way down, also not to potentially impact anything else in other places uses the `execDescribe` - since that method outputs a predictable format I just added a parses to convert it to json.

examples:

* No Flag
`go run main.go describe stream topic`
Fields
--------------------------------------------------------------------------------
USERID  bigint
FIRST_NAME      string
LAST_NAME       string
NICKNAMES       array(string)
Gender  boolean
ADDRESS struct(STREET_NAME string, NUMBER bigint)

DATASOURCE: users
FORMAT: JSON
KEY: USERID

* With flag
`go run main.go describe stream topic -json`
{
        "Fields": [
                {
                        "Name": "USERID",
                        "Type": "bigint"
                },
                {
                        "Name": "FIRST_NAME",
                        "Type": "string"
                },
                {
                        "Name": "LAST_NAME",
                        "Type": "string"
                },
                {
                        "Name": "NICKNAMES",
                        "Type": "array(string)"
                },
                {
                        "Name": "Gender",
                        "Type": "boolean"
                },
                {
                        "Name": "ADDRESS",
                        "Type": "struct(STREET_NAME string, NUMBER bigint)"
                }
        ],
        "Options": {
                "DATASOURCE:": "users",
                "FORMAT:": "JSON",
                "KEY:": "USERID"
        }
}

2023-10-06 01:37 UTC, ngjaying commented
> Any insight on why the test is failing? 
> looks like in the redis pubsub module but not sure why other than maybe test timing out?

Looks like your change has nothing to do with the failure, I just rerun the test.

2023-10-07 03:13 UTC, Rui-Gan requested changes

2023-10-07 03:13 UTC, Rui-Gan commented on internal/processor/stream_test.go
> +	input := "Fields\n--------------------------------------------------------------------------------\nUSERID\tbigint\nFIRST_NAME\tstring\nLAST_NAME\tstring\nNICKNAMES\t" +
It would be helpful if you could modify it to align with the format of other tests in the project, making it easier to add new tests.

2023-10-07 04:30 UTC, Rui-Gan commented on internal/processor/stream_test.go
> +	input := "Fields\n--------------------------------------------------------------------------------\nUSERID\tbigint\nFIRST_NAME\tstring\nLAST_NAME\tstring\nNICKNAMES\t" +
cool, what I meant was that you can enhance the code by incorporating the following structure, which allows to conveniently add test samples in the future:
``` go
tests := []struct {
		input   string
		want   string
		err string
	}{}
```

This approach simplifies the process of adding new test cases at a later stage.

2023-10-08 04:01 UTC, Rui-Gan approved these changes

2023-10-08 04:04 UTC, ngjaying commented
Will merge this one. Please add another PR to update the doc. Thanks.

2023-10-08 04:04 UTC, merged