fix: fix and test array function if has nil
lf-edge/ekuiper pull request #2581
Opened 2024-01-24 07:56 UTC by Yisaer

2024-01-25 08:03 UTC, ngjaying requested changes
The array functions should support nil array instead of just throw out an error. Please go through all functions and check.

2024-01-25 08:03 UTC, ngjaying commented on internal/binder/function/funcs_array.go
>  		val: func(ctx api.FunctionContext, args []ast.Expr) error {
If array is nil, should just return nil instead of error?

2024-01-26 01:03 UTC, Yisaer commented on internal/binder/function/funcs_array.go
> -	builtins["array_position"] = builtinFunc{
it's duplicated.

2024-01-29 05:07 UTC, ngjaying requested changes
array_concat doc is not updated

2024-01-29 05:07 UTC, ngjaying commented on docs/en_US/guide/sources/plugin/sql.md
> +
Don't remove this

2024-01-29 05:07 UTC, ngjaying commented on docs/zh_CN/sqls/functions/array_functions.md
> +返回一个去重的数组，即将数组中的重复元素去除。array 为 nil 时则固定返回 0。
return nil

2024-01-29 05:07 UTC, ngjaying commented on docs/zh_CN/sqls/functions/array_functions.md
> +返回一个新的数组，其中包含对给定数组中的每个元素应用给定函数的结果。array 为 nil 时则固定返回 0。
return nil

2024-01-29 05:08 UTC, ngjaying requested changes

2024-01-29 05:08 UTC, ngjaying commented on docs/en_US/guide/sinks/overview.md
> +| resendIndicatorField | string: default to global definition | field name of the resend cache, the field type must be a bool value. If the field is set, it will be set to true when resending. e.g.,
why change this file, it is irrelevant. The sme to sql.md

2024-01-29 06:53 UTC, ngjaying approved these changes

2024-01-29 07:03 UTC, merged