refactor(*): update product name in docs
lf-edge/ekuiper pull request #840
Opened 2021-06-17 10:09 UTC by ngjaying

Signed-off-by: ngjaying <ngjaying@gmail.com>

2021-06-17 10:37 UTC, Rory-Z approved these changes

2021-06-19 02:02 UTC, jinfahua requested changes

2021-06-19 03:17 UTC, ngjaying commented on deploy/chart/kuiper/README.md
> +    $ cd ekuiper/deploy/chart/Kuiper
if clone from new repo url https://github.com/lf-edge/ekuiper, then yes

2021-06-19 03:18 UTC, ngjaying commented on deploy/chart/kuiper/README.md
> +    + Search eKuiper
No, the helm chart name is not updated yet

2021-06-19 03:19 UTC, ngjaying commented on deploy/chart/kuiper/README.md
> ++ eKuiper realized persisted  `pods` through creating PVC resources and mount `/ekuiper/data` directory. **Before deploying Kuiper, user need to create PVC or Storage Classes resource in Kubernetes.*
yes

2021-06-19 03:24 UTC, ngjaying commented on deploy/chart/kuiper/README.md
> +    + Search eKuiper
revert back to Search Kuiper

2021-06-19 05:44 UTC, jinfahua approved these changes

2021-06-19 05:52 UTC, merged