update plugin tutorial for english version
lf-edge/ekuiper pull request #907
Opened 2021-07-26 08:33 UTC by SuperRxan

Signed-off-by: Jianxiang Ran <rxan_embedded@163.com>
update plugin tutorial for english version

2021-07-27 01:10 UTC, ngjaying requested changes

2021-07-27 01:10 UTC, ngjaying commented on docs/en_US/plugins/plugins_tutorial.md
> +Developing plugin is generally carried out in the development environment. eKuiper plugins will be deployed to the production environment after passing debugging and running the development environme
create **the** plugin project ?

2021-07-27 01:10 UTC, ngjaying commented on docs/en_US/plugins/plugins_tutorial.md
> +### Create plugin project inside eKuiper
Add "the" ?

2021-07-27 01:10 UTC, ngjaying commented on docs/en_US/plugins/plugins_tutorial.md
> +When user develop the plugin by this way, he must firstly download the eKuiper source code and run `make` command inside the eKuiper root directory. There are some plugin examples in the *extensions*
When users develop or when the user develops.  This problem also happens elsewhere, search user to check

2021-07-27 03:37 UTC, SuperRxan commented on docs/en_US/plugins/plugins_tutorial.md
> +Developing plugin is generally carried out in the development environment. eKuiper plugins will be deployed to the production environment after passing debugging and running the development environme
ack

2021-07-27 08:48 UTC, ngjaying requested changes

2021-07-27 08:48 UTC, ngjaying commented on docs/en_US/plugins/plugins_tutorial.md
>      docker run -d --name kuiper-dev --mount type=bind,source=/var/git,target=/home lfedge/ekuiper:0.3.0-dev
Try to use 1.3.0

2021-07-27 08:48 UTC, ngjaying commented on docs/zh_CN/plugins/plugins_tutorial.md
> +	//The db connection instance
Should revert to Chinese

2021-07-27 08:54 UTC, SuperRxan commented on docs/zh_CN/plugins/plugins_tutorial.md
> +	//The db connection instance
ack

2021-07-27 10:32 UTC, ngjaying requested changes

2021-07-27 10:32 UTC, ngjaying commented on docs/zh_CN/plugins/plugins_tutorial.md
> +插件原则上应该与生产环境 eKuiper 采用相同环境进行编译。假设生产环境为 eKuiper docker，则应当采用与生产环境相同版本的 dev docker 环境编译插件。例如，生产环境采用 [lfedge/ekuiper:0.4.0-alpine](https://registry.hub.docker.com/layers/lfedge/ekuiper/0.4.0-alpine/ima
-alpine is wrong. Should be 0.4.0-slim

2021-07-28 02:36 UTC, ngjaying approved these changes

2021-07-28 03:57 UTC, merged